### ISSUE TITLE
Problem with qstrreplace()

### ISSUE THREAD

**Issue by darkstar999** [wolkykim/qlibc#57] opened 2016-08-24 13:39 UTC
I use it to replace space in a exec string and it fails. The string was something like "/home/user/test/project/progs/cprogs/this is.sh"  and the function destroys the string. If I use the function for "this is.sh" everything is right.  I try to replace the " " with "\\ " to escape the space for exec.

**Comment by wolkykim** [comment] 2016-08-24 19:03
Can you provide the code?

**Comment by wolkykim** [comment] 2016-09-03 08:31
Ping. I don't hear back from you. Closing for now. Please re-open ticket if you believe the problem is from qlibc.

**Closed by wolkykim** 2016-09-03 08:31 UTC
